# Generated by Django 4.0.2 on 2022-02-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='category_id',
        ),
        migrations.AddField(
            model_name='advert',
            name='category_id',
            field=models.ManyToManyField(to='ads.Categories'),
        ),
    ]
