# Generated by Django 4.0.2 on 2022-02-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
