# Generated by Django 4.0.2 on 2022-02-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
