# Generated by Django 4.0.2 on 2022-02-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_advert_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
